package com.jalagama.newsapp_mvvm_architecture.utils

object Countries {

    val countryList = listOf<Pair<String, String>>(
        "ae" to "United Arab Emirates",
        "ar" to "Argentina",
        "at" to "Austria",
        "au" to "Australia",
        "be" to "Belgium",
        "bg" to "Bulgaria",
        "br" to "Brazil",
        "ca" to "Canada",
        "ch" to "Switzerland",
        "cn" to "China",
        "co" to "Colombia",
        "cu" to "Cuba",
        "cz" to "Czech Republic",
        "de" to "Germany",
        "eg" to "Egypt",
        "fr" to "France",
        "gb" to "United Kingdom",
        "gr" to "Greece",
        "hk" to "Hong Kong",
        "hu" to "Hungary",
        "id" to "Indonesia",
        "ie" to "Ireland",
        "in" to "India",
        "it" to "Italy",
        "jp" to "Japan",
        "kr" to "South Korea",
        "lt" to "Lithuania",
        "lv" to "Latvia",
        "ma" to "Morocco",
        "nz" to "New Zealand",
        "ng" to "Nigeria",
        "nl" to "Netherlands",
        "no" to "Norway",
        "ph" to "Philippines",
        "pl" to "Poland",
        "pt" to "Portugal",
        "ro" to "Romania",
        "rs" to "Serbia",
        "ru" to "Russia",
        "sa" to "Saudi Arabia",
        "uk" to "United Kingdom",
        "se" to "Sweden",
        "sg" to "Singapore",
        "si" to "Slovenia",
        "sk" to "Slovakia",
        "th" to "Thailand",
        "tr" to "Turkey",
        "tw" to "Taiwan",
        "us" to "United states of America",
        "za" to "South Africa",
        "ve" to "Venezuela"
    ).sortedBy { it.second }
}